spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookmanager?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true